default:
  image: ruby:3.2
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/ruby
  before_script:
    - ruby -v
    - apt update && apt install nodejs
    - node -v
    - gem install bundler -v 2.1.4
    - bundler -v
    - bundle install -j $(nproc) --path vendor/ruby

stages:
  - build
  - deploy
  - postdeploy

jekyll:
  stage: build
  variables:
    JEKYLL_ENV: "production"
  script:
    - bundle exec jekyll build
  artifacts:
    paths:
      - _site

pages:
  stage: deploy
  script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master

algolia:
  stage: postdeploy
  script:
    - bundle exec jekyll algolia
  only:
    - master
